### ISSUE TITLE
重启后显示未正确接收令牌

### ISSUE THREAD

**Issue by sukanka** [Magisk-Modules-Repo/Shizuku-boot#1]
每次重启后都这样, 还是需要手动点击一次.
device: oneplus A3000.
 Android version: 8.0.0,
 magisk version: 16.7, 17.0.
![image](https://user-images.githubusercontent.com/31362108/44945877-002ffa00-ae24-11e8-82a1-f7af7318c0db.png)

**Comment by Hill-98** [comment]
这个问题我没有遇到过，等我找台一加手机排查一下。

**Comment by Hill-98** [comment]
你可以先尝试一下允许 Shizuku Manager 自启动。

**Comment by sukanka** [comment]
Oxygen OS 没有自启动管理, appops 里面允许了自启动,又更新了V2版的shizuku boot, 仍然无效

**Comment by Hill-98** [comment]
这个问题我暂时没法排查，我朋友的一加手机没有root，我估计是因为 Shizuku Manager 没有被唤醒接受令牌。

**Comment by sukanka** [comment]
恢复出厂设置之后,重新刷了系统之后能够自启动了,并且能够正确获取令牌.
